# Site settings
title: gentoo.de

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "tyrian"

# No slash at the end
cdnurl: https://assets.gentoo.org
contact: https://www.gentoo.org/main/en/contact.xml
copyrightyears: "2001&ndash;2020"
